# Generated by Django 3.2 on 2021-09-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='ruta',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_control',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
